# Imports

In [6]:
import os
import numpy as np

import open3d as o3d

In [34]:
mesh = o3d.io.read_triangle_mesh("../../local_data/unbiased_mesh_atlas/body/female/avg/body.ply")
vertices = np.asarray(mesh.vertices)
# o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True, mesh_show_back_face=True)

new_vertices = []
for vertex in vertices:
    vertex = np.add(vertex,[0,0,3])
    new_vertices.append(vertex)

min_z = vertices[:, 2].min()
max_z = vertices[:, 2].max()
print(min_z)
print(max_z)

# mesh.vertices = o3d.utility.Vector3dVector(np.asarray(new_vertices))
# o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True, mesh_show_back_face=True)

0.011696
0.987518


In [29]:
x = (3 - min_z) / (max_z - min_z)
x

3.06234538676111

In [44]:
mesh = o3d.io.read_triangle_mesh("../../local_data/unbiased_mesh_atlas/body/female/avg/body.ply")
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True, mesh_show_back_face=True)
# Define the scaling factor for the z-direction
z_scaling_factor = 3

# Modify the z-coordinates of the mesh vertices
vertices = np.asarray(mesh.vertices)
print(vertices[0])
vertices[:, 2] *= z_scaling_factor
print(vertices[0])

min_z = vertices[:, 2].min()
max_z = vertices[:, 2].max()
print(min_z)
print(max_z)

#normalise values
# z_values = vertices[:, 2]
# normalized_z_values = (z_values - min_z) / (max_z - min_z)
# vertices[:, 2] = normalized_z_values

mesh.vertices = o3d.utility.Vector3dVector(vertices)

print(vertices[0])

# Visualize the stretched mesh
o3d.visualization.draw_geometries([mesh], mesh_show_wireframe=True, mesh_show_back_face=True)

[-0.41416   0.264352  0.607409]
[-0.41416   0.264352  1.822227]
0.035088
2.962554
[-0.41416   0.264352  1.822227]
